apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  namespace: default
  annotations:
    yalo.com/source: https://knative.dev/docs/eventing/sources/kafka-source/#create-a-kafka-topic
spec:
  template:
    spec:
      containers:
        - # This corresponds to
          # https://github.com/knative/eventing/tree/main/cmd/event_display/main.go
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
